# Copyright salsa-ci-team and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.

include:
 - .images-ci.yml

variables:
  VENDOR: debian
  RELEASE: sid

.build_only_sid: &build_only_sid
  extends: .build_template
  only:
    variables:
      - $RELEASE == 'sid'

#
# These images build only for sid.
#
amd64:aptly:
  extends: .build_only_sid

amd64:autopkgtest:
  extends: .build_only_sid

amd64:blhc:
  extends: .build_only_sid

amd64:gbp:
  extends: .build_only_sid

amd64:pipeline:
  extends: .build_only_sid

amd64:piuparts:
  extends: .build_only_sid

amd64:reprotest:
  extends: .build_only_sid

#
# These images build for all the releases.
#
amd64:base:
  extends: .build_template

amd64:dockerbuilder:
  extends: .build_template

amd64:lintian:
  extends: .build_template
  only:
    variables:
      # Use != to avoid overriding template except.
      - $RELEASE != 'experimental'

amd64:generic_tests:
  extends: .build_template

#
# Images for ARM jobs.
#
arm64:gbp:
  extends: .build_template
  tags:
    - arm64

arm64:dockerbuilder:
  extends: .build_template
  tags:
    - arm64

#
# Trigger build of other releases.
#
trigger other releases:
  extends: .trigger_build
  variables:
    RELEASES_LIST: 'jessie stretch stretch-backports buster buster-backports bullseye bullseye-backports experimental'
